apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlnk-agent-manager
  namespace: dlnk-predator
  labels:
    app: dlnk-agent-manager
    component: core
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dlnk-agent-manager
  template:
    metadata:
      labels:
        app: dlnk-agent-manager
        component: core
    spec:
      serviceAccountName: agent-manager-sa
      containers:
      - name: agent-manager
        image: dlnk-predator/agent-manager:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8002
          name: http
          protocol: TCP
        env:
        - name: REDIS_HOST
          value: "redis-cluster"
        - name: REDIS_PORT
          value: "6379"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: AGENT_IMAGE_REGISTRY
          value: "dlnk-predator"
        - name: MAX_CONCURRENT_AGENTS
          value: "100"
        - name: AGENT_TIMEOUT
          value: "3600"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8002
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: agent-manager-service
  namespace: dlnk-predator
spec:
  selector:
    app: dlnk-agent-manager
  ports:
  - protocol: TCP
    port: 8002
    targetPort: 8002
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-manager-sa
  namespace: dlnk-predator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agent-manager-role
  namespace: dlnk-predator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/status"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent-manager-rolebinding
  namespace: dlnk-predator
subjects:
- kind: ServiceAccount
  name: agent-manager-sa
  namespace: dlnk-predator
roleRef:
  kind: Role
  name: agent-manager-role
  apiGroup: rbac.authorization.k8s.io

