apiVersion: apps/v1
kind: Deployment
metadata:
  name: manus-ai-attack-platform
  namespace: manus-production
  labels:
    app: manus-ai-attack-platform
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: manus-ai-attack-platform
  template:
    metadata:
      labels:
        app: manus-ai-attack-platform
    spec:
      serviceAccountName: manus-service-account
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: manus-api
        image: manus-ai-attack-platform:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: manus-config
        - secretRef:
            name: manus-secrets
        env:
        - name: PYTHONPATH
          value: "/app"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONFAULTHANDLER
          value: "1"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: manus-service
  namespace: manus-production
  labels:
    app: manus-ai-attack-platform
spec:
  selector:
    app: manus-ai-attack-platform
  ports:
  - port: 80
    targetPort: 8000
    name: http
  type: ClusterIP
