name: "Attack Post-Exploitation Workflow"
description: "Post-exploitation activities including privilege escalation, persistence, and data exfiltration"
version: "1.0"

phases:
  - name: "Shell Upgrade & Stabilization"
    condition: "action == 'shell' or action == 'all'"
    agents:
      - name: "ShellManagerAgent"
        config:
          upgrade_to_pty: true
          stabilize_shell: true
          background_shell: true
      
      - name: "C2Agent"
        config:
          establish_beacon: true
          encryption: true
          stealth_mode: true

  - name: "Initial Enumeration"
    agents:
      - name: "PostExAgent"
        config:
          system_info: true
          user_info: true
          network_info: true
          process_info: true
          installed_software: true
      
      - name: "InternalNetworkMapperAgent"
        config:
          scan_internal: true
          identify_targets: true
          map_topology: true

  - name: "Privilege Escalation"
    condition: "action == 'privesc' or action == 'all'"
    agents:
      - name: "PrivilegeEscalationAgent"
        config:
          linux_scripts: ["linpeas", "linenum"]
          windows_scripts: ["winpeas", "powerup"]
          kernel_exploits: true
          suid_binaries: true
          sudo_misconfig: true
          cron_jobs: true
          writable_paths: true
      
      - name: "KernelExploitAgent"
        config:
          auto_exploit: true
          verify_kernel_version: true
      
      - name: "MetasploitPrivescAgent"
        config:
          suggest_exploits: true
          auto_exploit: true

  - name: "Credential Harvesting"
    agents:
      - name: "CredentialHarvesterAgent"
        config:
          memory_dump: true
          config_files: true
          browser_passwords: true
          ssh_keys: true
          database_credentials: true
      
      - name: "MimikatzAgent"
        condition: "os == 'windows'"
        config:
          dump_lsass: true
          dump_sam: true
          kerberos_tickets: true

  - name: "Lateral Movement"
    agents:
      - name: "LateralMovementAgent"
        config:
          ssh_keys: true
          pass_the_hash: true
          psexec: true
          wmi: true
          rdp: true
      
      - name: "ActiveDirectoryAgent"
        condition: "domain_joined == true"
        config:
          bloodhound: true
          kerberoasting: true
          asreproasting: true
          dcsync: true

  - name: "Persistence"
    condition: "action == 'backdoor' or action == 'all'"
    agents:
      - name: "PersistenceAgent"
        config:
          cron_backdoor: true
          ssh_key_injection: true
          service_backdoor: true
          startup_scripts: true
          scheduled_tasks: true
      
      - name: "BackdoorAgent"
        config:
          web_backdoor: true
          binary_backdoor: true
          rootkit: false  # Too aggressive
          c2_persistence: true

  - name: "Data Discovery"
    condition: "action == 'dump' or action == 'all'"
    agents:
      - name: "DataDiscoveryAgent"
        config:
          sensitive_files: true
          database_discovery: true
          cloud_credentials: true
          api_keys: true
          source_code: true
      
      - name: "DatabaseDumperAgent"
        config:
          mysql: true
          postgresql: true
          mssql: true
          mongodb: true
          redis: true

  - name: "Data Exfiltration"
    condition: "action == 'dump' or action == 'all'"
    agents:
      - name: "DataDumperAgent"
        config:
          compress: true
          encrypt: true
          split_files: true
          max_size_mb: 100
      
      - name: "ExfiltrationAgent"
        config:
          methods: ["http", "dns", "icmp"]
          stealth_mode: true
          rate_limit: true
          chunk_size: "1MB"

  - name: "Defense Evasion"
    agents:
      - name: "LogCleanerAgent"
        config:
          clear_bash_history: true
          clear_system_logs: false  # Too obvious
          timestamp_manipulation: true
      
      - name: "AntiForensicsAgent"
        config:
          clear_artifacts: true
          timestomp: true
          secure_delete: true

  - name: "Reporting & Cleanup"
    agents:
      - name: "ReportingAgent"
        config:
          format: "json"
          include_credentials: true
          include_files: true
          include_shell_access: true
          include_persistence: true
      
      - name: "SessionManagerAgent"
        config:
          maintain_access: true
          cleanup_tools: false  # Keep for persistence
          remove_logs: false

settings:
  parallel_execution: false  # Sequential for post-exploitation
  max_concurrent_agents: 2
  timeout_per_agent: 1200
  retry_on_failure: true
  max_retries: 2
  continue_on_error: true
  save_intermediate_results: true
  stealth_mode: false
  aggressive_mode: true

