global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'manus-production'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  # - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Main API
  - job_name: 'manus-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8000']
        labels:
          service: 'api'

  # C2 Server
  - job_name: 'manus-c2'
    metrics_path: '/metrics'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['c2-server:8443']
        labels:
          service: 'c2'

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']
        labels:
          service: 'database'

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
        labels:
          service: 'cache'

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
        labels:
          service: 'proxy'

  # Node exporter (if added)
  - job_name: 'node'
    static_configs:
      - targets: []
        labels:
          service: 'node'

